language: node_js
node_js:
    - "stable"
cache:
  directories:
    - node_modules

before_deploy:
    - yarn build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
      branch: main
